# Introduction to Programming Syllabus
- Variables, assignments
- Simple input
- Main program
- If-statement
- Logical operators
- Loops
- Output formatting
- Functions
- Parameters, return values
- Debugger
- Lists
- Strings
- Dictionary
- Values and references
- Basics of program design
- Programming style
- Exceptions
- File handling
- Classes and objects
